services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - "127.0.0.1:8080:80" 
    volumes:
      - /etc/localtime:/etc/localtime:ro # mount global
      - ./nginx.conf:/etc/nginx/nginx.conf # mount single file
      - ./sites:/mnt # mount dir
      - shared:/data # mount volume