name: Release
on: [push]

permissions:
  id-token: write
  contents: write

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare data
        run: |
          cd test-data
          docker compose -f docker-compose.yaml -f docker-compose.2.yaml create --pull missing
          docker compose -f docker-compose.yaml -f docker-compose.2.yaml up -d
          cd ../
          echo "waiting for start"
          sleep 5

          # add data to shared volume
          cd test-data
          echo "Payload" | docker compose -f docker-compose.yaml -f docker-compose.2.yaml exec -T dummy /bin/sh -c 'cat - > /data/helloworld'
          cd ../

      - name: Initial check
        run: |
          data="$(curl -v http://127.0.0.1:8080/helloworld)"
          [ "$data" = "Payload" ]

      - name: Create backup
        run: |
          rm -rf backups
          ./dkp/dkp.py -o backups/output.bin -p foobar test-data

      - name: Cleanup
        run: |
          docker stop $(docker ps -q)
          docker rm $(docker ps -aq)
          docker volume rm $(docker volume ls -q)
          docker rmi $(docker images -aq)

      - name: Restore and start
        run: |
          cd backups
          ./output.bin -r -s foobar
          cd ..
          echo "waiting..."
          sleep 5

      - name: Check
        run: |
          data="$(curl -v http://127.0.0.1:8080/helloworld)"
          [ "$data" = "Payload" ]
